{
"installed":
{"client_id":
"779754168245-v6eidqsepsap04psnhkp25b0f02k7dno.apps.googleusercontent.com",
"project_id":"karmawebv1",
"auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token",
"auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
"client_secret":"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",
"redirect_uris":["http://localhost"]}}