name: Android CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Decode keystore
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 -d > app/my-release-key.keystore

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKey: app/my-release-key.keystore
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        id: sign_apk
        env:
          OUTPUT_PATH: signed-app-release.apk

      - name: Decode Firebase service account
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > app/google-services.json

      - name: Upload to Firebase App Distribution
        run: ./gradlew appDistributionUploadRelease
        env:
          FIREBASE_APP_ID: 1:779754168245:android:3b9ea15bc15fc531d083fc # Replace with your Firebase App ID
